version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    groups:
      vite:
        patterns:
          - "vite"
          - "@vitejs/*"
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      testing:
        patterns:
          - "@testing-library/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
    ignore:
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
